services:
  nodecast-tv:
    image: ghcr.io/technomancer702/nodecast-tv:latest
    build: https://github.com/technomancer702/nodecast-tv.git#main
    container_name: nodecast-tv
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.nodecast-tv.rule=Host(`oziplay.duckdns.org`)"
      - "traefik.http.routers.nodecast-tv.entrypoints=websecure"
      - "traefik.http.routers.nodecast-tv.tls.certresolver=myresolver"

      - "traefik.http.services.nodecast-tv.loadbalancer.server.port=4000"

    environment:
      - NODE_ENV=production
      - PORT=4000 # Optional: Internal container port
networks:
  traefik-network:
    external: true
